### ISSUE TITLE
百度搜索侧边栏没有搜索结果

### ISSUE THREAD

**Issue by improve100** [zhengbangbo/chat-gpt-userscript#17]
![image](https://user-images.githubusercontent.com/6092914/210119733-eda9def7-b37b-4240-a918-8866f6181a8e.png)
![image](https://user-images.githubusercontent.com/6092914/210119741-ae12baee-b713-40d0-a95f-58a1cbdab4eb.png)

**Comment by zhengbangbo** [comment]
麻烦提供一下这些信息：
 - OS: [e.g. Windows, macOS, iOS]
 - Browser: [e.g. Chrome, Firefox, Safari]
 - Userscript Manager: [e.g. Tampermonkey, Violentmonkey]
 - Userscript Version: [e.g. v0.3.4]

**Comment by zhengbangbo** [comment]
之前 https://github.com/zhengbangbo/chat-gpt-userscript/issues/7 有碰到类似的问题。我这边后来没复现了，你是这种情况吗？

**Comment by improve100** [comment]
OS: ubuntun2004
Browser: Chrome
Userscript Manager: Tampermonkey
Userscript Version: v0.8.0

我不太熟悉js代码， 有更详细的修复说明吗？

**Comment by zhengbangbo** [comment]
1）控制台有报错吗？
2）无论刷新还是重新搜索都不显示搜索结果吗？

我这边没有 Ubuntu 环境。修复的话要看是什么问题导致的，我也不太能猜出来。

**Comment by zhengbangbo** [comment]
1）在百度搜索页面，先看看 Tampermonkey 的脚本有没有触发。
2）如果有触发，再看看控制台有没有报错，可能是搜索结果的 container 没有注入成功。
3）如果你有能力抓包，可以看看给到 openai.com 的请求有没有成功发出去。不过你这里没显示估计也和请求关系不大，大概是请求之前的问题。

**Comment by improve100** [comment]
点击百度一下蓝色按钮没有显示，但是刷新网页可以出来。

**Comment by pwelyn** [comment]
是需要登录才可以使用的吗

**Comment by zhengbangbo** [comment]
> 是需要登录才可以使用的吗

是的，需要有 openai 帐号
