### ISSUE TITLE
希望支持 bing /百度  搜索

### ISSUE THREAD

**Issue by hyh1750522171** [zhengbangbo/chat-gpt-userscript#2]
作者你好，脚本可以增加支持bing  和百度搜索吗？？

**Comment by zhengbangbo** [comment]
可以增加的。如果你有能力也欢迎提交 PR，只需要判断当前 URL，定位对象加入 container。

**Comment by hyh1750522171** [comment]
你好，我在油猴插件商店看到有人支持bing了，是通过你的代码
https://greasyfork.org/zh-CN/scripts/456131-chatgpt-tools-plus

**Comment by zhengbangbo** [comment]
刚发布了 [V0.3](https://greasyfork.org/scripts/456077?version=1125675) 版本添加了这些搜索引擎支持。
