### ISSUE TITLE
使用中的问题 

### ISSUE THREAD

**Issue by hyh1750522171** [zhengbangbo/chat-gpt-userscript#5]
1. 在国内使用这个，特别的慢，还会会出现没有内容情况（特别多）
2. 可以添加，对话窗口吗？

**Comment by zhengbangbo** [comment]
- 回答越长，需要等待的时间就会越长。如果 https://github.com/zhengbangbo/chat-gpt-userscript/issues/1 解决了，就可以实现官网同样的逐字打印效果，那个时候体验就会比较好了。

- 没有内容的情况是指什么样的？各种情况可能情况不太一样。麻烦提供一下是什么浏览器，使用什么 userscript 管理器。
  1. 始终不显示「Waiting for ChatGPT response...」这句话
  2. 停留在「Waiting」
  3. 出现「Waiting」后整个框变空白？

- 这个脚本使用对话窗口，可以尝试一下：https://greasyfork.org/scripts/456131

- 对话窗口目前对本项目来说优先级不高，后续看情况是否添加，完成连续对话什么的

**Comment by hyh1750522171** [comment]
好的。谢谢大佬

**Comment by hyh1750522171** [comment]
我不会js。期待快快更新。。。

**Comment by zhengbangbo** [comment]
> 出现没有内容情况

有的时候是每行文本太宽，容器自适应到页面最下面去了。刚在[v0.3.6](https://greasyfork.org/scripts/456077-chat-gpt-search-sidebar?version=1126422)修复了。

这两天在尝试一个大的重构，过不久会发出来。
